seed: 42

data:
  root: "data/chest_xray"
  img_size: 224
  batch_size: 64
  num_workers: 4
  val_split_from_train: 0.20 # 20% validation - זה יתן ~1000 תמונות val
  balance_sampler: false
  strong_augment: true

train:
  epochs: 10 # במקום 15 - לא מוגזם
  lr: 0.0005 # קצת נמוך יותר לstability
  weight_decay: 0.0001
  optimizer: adamw
  scheduler: cosine
  warmup_epochs: 3
  amp: true
  grad_clip: 1.0
  checkpoint_every: 5

model:
  type: cnn
  num_classes: 2

  cnn:
    name: custom
    pretrained: false
    freeze_backbone: false

  vit:
    patch_size: 14 # קטן יותר = יותר tokens = יותר detail
    dim: 512 # גדול יותר לlearning capacity
    depth: 6 # פחות layers = מהיר יותר, פחות overfitting
    heads: 8 # יותר attention heads
    mlp_ratio: 4
    drop_rate: 0.2 # יותר dropout

  # ViT-specific training settings
  train_vit:
    epochs: 10 # קצת יותר לViT
    lr: 0.0003 # נמוך יותר לViT
    weight_decay: 0.01 # יותר regularization
    warmup_epochs: 5 # יותר warmup לViT

log:
  out_dir: "outputs2"
  run_name: null
